---
name: Pull Request
on: pull_request
permissions: {}
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: gh -R "$GITHUB_REPOSITORY" pr merge ${{github.event.pull_request.number}} -ds
        env:
          GH_TOKEN: ${{ github.token }}
